language: python 
before_install: 
 - chmod +x ./flaskapp/st.sh 
install: 
 - pip3 install flask 
 - pip3 install gunicorn 
 - pip3 install requests 
 - pip3 install flask-bootstrap 
 - pip3 install flask-wtf
 - pip3 install pillow 
 - pip3 install tensorflow==2.0.0-alpha0 
 - pip3 install keras 

name: 'test my project'
on: [push]
jobs:
 checks:
 runs-on: ubuntu-latest
 steps:
- name: Install pipenv
 run: python -m pip install pipenv
 - name: Pipenvsync
 run: | 
 pipenv sync
 - name: Start tests
 run: pipenv run python -m pytest my_tests.py
 
script: 
 - cd flaskapp
 - ./st.sh
 
